services:
  - type: web
    name: repititor-uz
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2